/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tallerFicsa.proyectoSVentas.view;

import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tallerFicsa.proyectoSVentas.controller.IngresoJpaController;
import tallerFicsa.proyectoSVentas.controller.VentaJpaController;
import tallerFicsa.proyectoSVentas.entity.Ingreso;
import tallerFicsa.proyectoSVentas.entity.Venta;

/**
 *
 * @author Usuario
 */
public class ListadoVentaFrame1 extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
    private VentaJpaController ingobj = new VentaJpaController();
    private List<Venta> listaIngresos;
    private Venta ingreso = new Venta();

    /**
     * Creates new form ListadoIngresosFrame
     */
    public ListadoVentaFrame1() {
        initComponents();
        listarIngresos();
    }

    private void listarIngresos() {
        SimpleDateFormat formato = new SimpleDateFormat();
//        JButton btn = new JButton("...");
        model = (DefaultTableModel) tblDatos.getModel();
        if (model.getRowCount() > 0) {
            model.setNumRows(0);
        }
        Object[] obj = new Object[10];
        try {
            listaIngresos = ingobj.listarVentas();
            for (int i = 0; i < listaIngresos.size(); i++) {
                ingreso = (Venta) listaIngresos.get(i);
                obj[0] = ingreso.getIdventa();
                obj[1] = ingreso.getSerieComprobante();
                obj[2] = ingreso.getNumComprobante();
                obj[3] = ingreso.getTipoComprobante();
                obj[4] = ingreso.getIdcliente().getNombre();
                obj[5] = ingreso.getIdusuario().getNombre();
                obj[6] = ingreso.getTotalVenta();
                obj[7] = ingreso.getImpuesto();
                obj[8] = formato.format(ingreso.getFechaHora());
//                obj[9]= btn;
                model.addRow(obj);
            }
            tblDatos.setModel(model);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Error en el sistema", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnDetalleIngreso = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listado de Ventas");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("LISTADO DE VENTAS DE PRODUCTOS");

        tblDatos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Serie ", "Num Comprobante", "Tipo comprobante", "Proveedor", "Usuario", "Total Compra", "Impuesto", "Fecha y Hora"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblDatos.getColumnModel().getColumn(1).setPreferredWidth(15);
            tblDatos.getColumnModel().getColumn(7).setPreferredWidth(12);
        }

        btnDetalleIngreso.setText("VER DETALLE");
        btnDetalleIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDetalleIngreso)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnDetalleIngreso)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalleIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleIngresoActionPerformed
        if (tblDatos.getSelectedRowCount() == 1) {
            try {
                int row = tblDatos.getSelectedRow();
                int idIngreso = Integer.parseInt(tblDatos.getValueAt(row, 0).toString());
                if (JOptionPane.showConfirmDialog(null, "Quieres ver el detalle de este ingreso ?") == JOptionPane.YES_OPTION) {
                        ListaDetalleVentaFrame ldif = new ListaDetalleVentaFrame(idIngreso);
                       // ldif.setIdIngreso(idIngreso);
                        EmpleadoFrame.VentanaPrincipal.add(ldif);                        
                        ldif.setVisible(true);
                        
                } 

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ocurrio algun error", "Informacion", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(null, "Tiene que seleccionar algun registro", "Informacion", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnDetalleIngresoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalleIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
