/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tallerFicsa.proyectoSVentas.view;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import tallerFicsa.proyectoSVentas.controller.ArticuloJpaController;
import tallerFicsa.proyectoSVentas.controller.DetalleIngresoJpaController;
import tallerFicsa.proyectoSVentas.controller.DetalleVentaJpaController;
import tallerFicsa.proyectoSVentas.controller.IngresoJpaController;
import tallerFicsa.proyectoSVentas.controller.PersonaJpaController;
import tallerFicsa.proyectoSVentas.controller.VentaJpaController;
import tallerFicsa.proyectoSVentas.entity.Articulo;
import tallerFicsa.proyectoSVentas.entity.DetalleIngreso;
import tallerFicsa.proyectoSVentas.entity.DetalleVenta;
import tallerFicsa.proyectoSVentas.entity.Ingreso;
import tallerFicsa.proyectoSVentas.entity.Persona;
import tallerFicsa.proyectoSVentas.entity.Usuario;
import tallerFicsa.proyectoSVentas.entity.Venta;

/**
 *
 * @author Usuario
 */
public class VentaProductoFrame_1 extends javax.swing.JInternalFrame {

    String usuario;
    int idUsuario;
    DefaultTableModel modelo = new DefaultTableModel();
    VentaJpaController inct = new VentaJpaController();
    DetalleVentaJpaController dict = new DetalleVentaJpaController();

    DetalleVenta detalleing = new DetalleVenta();
    Venta ingobj = new Venta();
    Articulo articulo = new Articulo();
    Persona cliente = new Persona();
    int idArticulo;
    double tpagar;

    /**
     * Creates new form IngresoProductoFrame
     */
    public VentaProductoFrame_1() {
        initComponents();
        txtFecha.setText(ObtenerFecha());

    }

    public void setUsuario(String dato) {
        this.usuario = dato;
        txtUsuario.setText(this.usuario);
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtComprobante = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cboTipComprobante = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelCodProducto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarCLie = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        txtCodProducto = new javax.swing.JTextField();
        txtDocCliente = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        spinCantidad = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGenerarVenta = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtIGV = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Venta de Productos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel5.setBackground(new java.awt.Color(51, 204, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel1.setText("PUNTO DE VENTA DE PRODUCTOS");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Fecha Actual:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nro Serie:");

        txtSerie.setEditable(false);
        txtSerie.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtSerie.setForeground(java.awt.Color.blue);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Nro Comprobante:");

        txtComprobante.setEditable(false);
        txtComprobante.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtComprobante.setForeground(java.awt.Color.blue);

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtFecha.setForeground(java.awt.Color.blue);

        cboTipComprobante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta", "Factura" }));
        cboTipComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipComprobanteActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("TIPO COMPROBANTE:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerFicsa/proyectoSVentas/Images/ventas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboTipComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(5, 5, 5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(256, 256, 256))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboTipComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("DOC CLIENTE:");

        labelCodProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelCodProducto.setText("COD ARTICULO:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("DESCUENTO POR UNIDAD");

        btnBuscarCLie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerFicsa/proyectoSVentas/Images/buscar.png"))); // NOI18N
        btnBuscarCLie.setText("BUSCAR");
        btnBuscarCLie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCLieActionPerformed(evt);
            }
        });

        btnBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerFicsa/proyectoSVentas/Images/buscar.png"))); // NOI18N
        btnBuscarProd.setText("BUSCAR");
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });

        txtPrecioVenta.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("CLIENTE");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("PRODUCTO:");

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtCliente.setForeground(java.awt.Color.blue);
        txtCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtProducto.setEditable(false);
        txtProducto.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtProducto.setForeground(java.awt.Color.blue);
        txtProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerFicsa/proyectoSVentas/Images/add.png"))); // NOI18N
        btnAgregarProducto.setText("AGREGAR");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("STOCK:");

        txtStock.setEditable(false);
        txtStock.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtStock.setForeground(java.awt.Color.blue);
        txtStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("ATENDIDO POR:");

        txtUsuario.setEditable(false);
        txtUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtUsuario.setForeground(java.awt.Color.blue);
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("PRECIO VENTA:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("CANTIDAD:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(labelCodProducto)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7))
                        .addGap(1, 1, 1)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(txtPrecioVenta)
                    .addComponent(txtCodProducto)
                    .addComponent(txtDocCliente))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarCLie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txtProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnBuscarCLie)
                    .addComponent(txtDocCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodProducto)
                    .addComponent(btnBuscarProd)
                    .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarProducto)))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        tblDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDatos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "COD", "PRODUCTO", "CANTIDAD", "PRECIO UNITARIO COMPRA", "DESCUENTO UNITARIO COMPRA", " TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblDatos.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblDatos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblDatos.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblDatos.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblDatos.getColumnModel().getColumn(5).setPreferredWidth(10);
            tblDatos.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerFicsa/proyectoSVentas/Images/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerFicsa/proyectoSVentas/Images/calcular.png"))); // NOI18N
        btnGenerarVenta.setText("GUARDAR VENTA");
        btnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaActionPerformed(evt);
            }
        });

        jLabel13.setText("SUBTOTAL:");

        txtSubTotal.setEditable(false);

        jLabel17.setText("IGV(18%)");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerFicsa/proyectoSVentas/Images/money.png"))); // NOI18N
        jLabel18.setText("TOTAL A PAGAR:");

        txtIGV.setEditable(false);
        txtIGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIGVActionPerformed(evt);
            }
        });

        txtTotalPagar.setEditable(false);
        txtTotalPagar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(java.awt.Color.blue);
        jLabel19.setText("Ojo: Si el tipo de comprobante es Factura se aplicara un IGV(18%)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(189, 189, 189)
                            .addComponent(btnCancelar)
                            .addGap(18, 18, 18)
                            .addComponent(btnGenerarVenta)
                            .addGap(76, 76, 76)
                            .addComponent(jLabel18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel13)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarVenta)
                    .addComponent(btnCancelar))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        nuevo();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaActionPerformed
        if (txtTotalPagar.getText().equalsIgnoreCase("") || txtSerie.getText().equalsIgnoreCase("") || txtComprobante.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Ingrese datos por favor", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            guardarVenta();
            guardarDetalleVenta();
            actualizarStock();
            JOptionPane.showMessageDialog(this, "Se genero el ingreso exitosamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            nuevo();
        }

    }//GEN-LAST:event_btnGenerarVentaActionPerformed

    private void btnBuscarCLieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCLieActionPerformed
        buscarCliente();
    }//GEN-LAST:event_btnBuscarCLieActionPerformed

    private String ObtenerFecha() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);

    }

    public void nuevo() {
        limpiarTabla();
        txtDocCliente.setText("");
        txtCliente.setText("");
        txtCodProducto.setText("");
        txtProducto.setText("");
        txtDescuento.setText("");
        txtPrecioVenta.setText("");
        txtStock.setText("");
        txtSubTotal.setText("");
        txtIGV.setText("");
        txtTotalPagar.setText("");
        spinCantidad.setValue(0);
        txtDocCliente.requestFocus();
        txtSerie.setText("");
        txtComprobante.setText("");
    }

    public boolean validarCamposVacios() {
        if (txtCodProducto.getText().isEmpty() || txtProducto.getText().isEmpty()
                || txtPrecioVenta.getText().isEmpty() || txtDescuento.getText().isEmpty()
                || spinCantidad.getValue().toString().equalsIgnoreCase("0")) {
            return false;
        } else {
            return true;
        }
    }

    public void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        buscarProducto();
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        if (validarCamposVacios()) {
            agregarProducto();
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese todos los campos del articulo ", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void txtIGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIGVActionPerformed

    }//GEN-LAST:event_txtIGVActionPerformed

    private void cboTipComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipComprobanteActionPerformed
        if (cboTipComprobante.getSelectedItem().toString().equalsIgnoreCase("Boleta")) {
            txtSerie.setText("001");
            txtComprobante.setText(generarSerieBoleta());
            if (!txtSubTotal.getText().isEmpty()) {
                txtIGV.setText("0");
                double IGV = Double.parseDouble(txtIGV.getText());
                double SubTotal = Double.parseDouble(txtSubTotal.getText());
                double total = IGV + SubTotal;
                txtTotalPagar.setText("" + total);
            }
        } else {
            txtSerie.setText("0001");
            txtComprobante.setText(generarSerieFactura());
            if (!txtSubTotal.getText().isEmpty()) {
                txtIGV.setText("" + tpagar * 0.18);
                double IGV = Double.parseDouble(txtIGV.getText());
                double SubTotal = Double.parseDouble(txtSubTotal.getText());
                double Total = IGV + SubTotal;
                txtTotalPagar.setText("" + Total);
            }

        }
    }//GEN-LAST:event_cboTipComprobanteActionPerformed

    public String generarSerieBoleta() {
        VentaJpaController ingctr = new VentaJpaController();
        String serie = ingctr.maxNumComprobanteBoleta();
        String serieGenerada;
        if (serie == null) {
            serieGenerada = String.format("%06d", 1);
        } else {
            int increment = Integer.parseInt(serie);
            increment++;
            serieGenerada = String.format("%06d", increment);
        }

        return serieGenerada;
    }

    public String generarSerieFactura() {
        VentaJpaController ingctr = new VentaJpaController();
        String serie = ingctr.maxNumComprobanteFactura();
        String serieGenerada;
        if (serie == null) {
            serieGenerada = String.format("%06d", 1);
        } else {
            int increment = Integer.parseInt(serie);
            increment++;
            serieGenerada = String.format("%06d", increment);
        }

        return serieGenerada;
    }

    public void actualizarStock() {
        try {
            ArticuloJpaController articuloctrl = new ArticuloJpaController();

            for (int i = 0; i < modelo.getRowCount(); i++) {
                Articulo art = new Articulo();
                idArticulo = Integer.parseInt(tblDatos.getValueAt(i, 1).toString());
                int cant = Integer.parseInt(tblDatos.getValueAt(i, 3).toString());

                art = articuloctrl.findArticulo(idArticulo);

                int cantActual = art.getStock() - cant;

                art.setIdarticulo(idArticulo);
                art.setStock(cantActual);
                articuloctrl.edit(art);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se actualizo el stock- Error: " + e.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);

        }

    }

    public void buscarCliente() {
        int r;
        String codigo = txtDocCliente.getText();
        if (codigo.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un codigo de Cliente");
        } else {
            PersonaJpaController clie = new PersonaJpaController();
            cliente = clie.buscarClientexNumDocumento(codigo);
            if (cliente != null) {
                txtCliente.setText(cliente.getNombre());
            } else {
                r = JOptionPane.showConfirmDialog(this, "CLiente no encontrado, Desea añadir uno nuevo? ");
                if (r == 0) {
                    ClienteFrame prf = new ClienteFrame();
                    EmpleadoFrame.VentanaPrincipal.add(prf);
                    prf.setVisible(true);
                }
            }
        }
    }

    public void buscarProducto() {
        int r;
        String codigo = txtCodProducto.getText();
        if (codigo.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un codigo de producto");
        } else {
            ArticuloJpaController article = new ArticuloJpaController();
            DetalleIngresoJpaController article1 = new DetalleIngresoJpaController();
            articulo = article.buscarArticuloVxCodigo(codigo);
            if (articulo != null) {
                txtProducto.setText(articulo.getNombre());
                txtStock.setText(articulo.getStock().toString());
                if (ExtraerPrecioVenta(articulo.getIdarticulo().toString()).equalsIgnoreCase("vacio")) {
                    JOptionPane.showMessageDialog(this, "El articulo no tiene precio de venta registrado.En el menu de consulta de operaciones(Listado de Ingresos),revisa los articulos que si tengan");
                    txtProducto.setText("");
                    txtStock.setText("");
                } else {
                    txtPrecioVenta.setText(ExtraerPrecioVenta(articulo.getIdarticulo().toString()));
                }
            } else {
                r = JOptionPane.showConfirmDialog(this, "Articulo no encontrado, Desea añadir un nuevo registro? ");
                if (r == 0) {
                    ArticuloFrame arf = new ArticuloFrame();
                    AdministradorFrame.VentanaPrincipal.add(arf);
                    arf.setVisible(true);
                }
            }
        }
    }

    public String ExtraerPrecioVenta(String Codigo) {
        String r = "No Tiene";

        DetalleIngresoJpaController article = new DetalleIngresoJpaController();
        String articulo = article.ExtraerPrecioVenta(Codigo);
        if (articulo != null) {
            r = articulo;
        } else {
            JOptionPane.showConfirmDialog(this, "No se extrajo el precio de venta");

        }
        return r;
    }

    public void agregarProducto() {
        String tipoComprobante = cboTipComprobante.getSelectedItem().toString();
        double total;
        int item = 0;
        modelo = (DefaultTableModel) tblDatos.getModel();
        item++;
        idArticulo = articulo.getIdarticulo();
        String nomArticulo = txtProducto.getText();
        double precioVenta = Double.parseDouble(txtPrecioVenta.getText());
        double Descuento = Double.parseDouble(txtDescuento.getText());
        int cantidad = Integer.parseInt(spinCantidad.getValue().toString());
        total = (cantidad * precioVenta) - (cantidad * Descuento);
        ArrayList lista = new ArrayList();

        lista.add(item);
        lista.add(idArticulo);
        lista.add(nomArticulo);
        lista.add(cantidad);
        lista.add(precioVenta);
        lista.add(Descuento);
        lista.add(total);
        Object[] ob = new Object[7];
        ob[0] = lista.get(0);
        ob[1] = lista.get(1);
        ob[2] = lista.get(2);
        ob[3] = lista.get(3);
        ob[4] = lista.get(4);
        ob[5] = lista.get(5);
        ob[6] = lista.get(6);
        modelo.addRow(ob);
        tblDatos.setModel(modelo);
        calcularTotal(cantidad, precioVenta, tipoComprobante, Descuento);
    }

    public void calcularTotal(int cantidad, double precio, String tipoComprobante, double Descuento) {
        tpagar = 0;
        for (int i = 0; i < tblDatos.getRowCount(); i++) {
            cantidad = Integer.parseInt(tblDatos.getValueAt(i, 3).toString());
            precio = Double.parseDouble(tblDatos.getValueAt(i, 4).toString());
            Descuento = Double.parseDouble(tblDatos.getValueAt(i, 5).toString());
            tpagar = tpagar + ((cantidad * precio) - (cantidad * Descuento));
        }
        if (tipoComprobante.equalsIgnoreCase("Factura")) {
            txtSubTotal.setText("" + tpagar);
            txtIGV.setText("" + 0.18 * tpagar);
            double subTotal = Double.parseDouble(txtSubTotal.getText());
            double IGV = Double.parseDouble(txtIGV.getText());
            double totalPagar = subTotal + IGV;
            txtTotalPagar.setText("" + totalPagar);
        } else {
            txtSubTotal.setText("" + tpagar);
            txtIGV.setText("0");
            double subTotal = Double.parseDouble(txtSubTotal.getText());
            double IGV = Double.parseDouble(txtIGV.getText());
            double totalPagar = subTotal + IGV;
            txtTotalPagar.setText("" + totalPagar);
        }

    }

    public void guardarVenta() {
        Date fecha = new Date();
        Usuario us = new Usuario();
        int idUser = this.getIdUsuario();
        us.setIdusuario(idUser);
        int idCliente = cliente.getIdpersona();
        Persona CLI = new Persona();
        CLI.setIdpersona(idCliente);

        String tipoComprobante = cboTipComprobante.getSelectedItem().toString();
        String serie = txtSerie.getText();
        String comprobante = txtComprobante.getText();
        //String fecha = txtFecha.getText();
        double impuesto = Double.parseDouble(txtIGV.getText());

        double monto = Double.parseDouble(txtTotalPagar.getText());
        ingobj.setIdcliente(CLI);
        ingobj.setEstado("Aceptado");
        ingobj.setIdusuario(us);
        ingobj.setTipoComprobante(tipoComprobante);
        ingobj.setSerieComprobante(serie);
        ingobj.setNumComprobante(comprobante);

        ingobj.setFechaHora(fecha);
        ingobj.setImpuesto(BigDecimal.valueOf(impuesto));
        ingobj.setTotalVenta(BigDecimal.valueOf(monto));

        inct.create(ingobj);
    }

    public void guardarDetalleVenta() {
        Venta ing = new Venta();
        int idventa = inct.obtenerIdIngreso();
        ing.setIdventa(idventa);
        for (int i = 0; i < tblDatos.getRowCount(); i++) {
            int idArticulo = Integer.parseInt(tblDatos.getValueAt(i, 1).toString());
            int cantProducto = Integer.parseInt(tblDatos.getValueAt(i, 3).toString());
            double descuento = Double.parseDouble(tblDatos.getValueAt(i, 5).toString());
            double precioVentaProducto = Double.parseDouble(tblDatos.getValueAt(i, 4).toString());
            detalleing.setIdventa(ing);
            Articulo objart = new Articulo();
            objart.setIdarticulo(idArticulo);
            detalleing.setIdarticulo(objart);
            detalleing.setDescuento(BigDecimal.valueOf(descuento));
            detalleing.setPrecioVenta(BigDecimal.valueOf(precioVentaProducto));
            detalleing.setCantidad(cantProducto);
            dict.create(detalleing);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarCLie;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarVenta;
    private javax.swing.JComboBox<String> cboTipComprobante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodProducto;
    private javax.swing.JSpinner spinCantidad;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtComprobante;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDocCliente;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotalPagar;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
